name: socket_com
description: A flutter , dart package for socket communication safely this package enables client to listen to difference event from server also can  register new events to register to , need to configure this events from server to send data accordingly.

repository: https://github.com/shreyasSarve/socket_communication

version: 0.0.1+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
